In [1]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [2]:
db = datasets.load_iris()
x_train, x_test, y_train, y_test = train_test_split(db.data, db.target, test_size = 0.2)
print(x_train.shape, y_train.shape , x_test.shape, y_test.shape)

(120, 4) (120,) (30, 4) (30,)


In [4]:
algo1 = LinearRegression()
cross_val_score(algo1, x_train, y_train, cv =3)

array([0.93597666, 0.86984052, 0.91474505])

In [10]:
cross_val_score(algo1 , db.data, db.target, cv =3)

#this is because we have the dataset as 3 sets of 50 each and all of them are sorted so 0 score

array([0., 0., 0.])

In [9]:
from sklearn.model_selection import KFold
cross_val_score(algo1 , db.data, db.target, cv = KFold(3, True, 0))
#Now we have shuffled and then split the dataset

array([0.90322728, 0.92527008, 0.94214064])