This Section will be for Feature Scaling , why used , where used etc = <br>
we use this as a part of data preprocessing , before applying any algo , model or regressonr , classifier etc <br>
we want all the features to lie in an unifrom range (usually waht happens is that the feature with a range of higher values overpowers the features with lower valued ranges for most algorithms , to remove this feature scaling is important)
<br> <br>
important example - find nearest neighbour - housing are sqft(range-1000,2000) , noofbedrooms(range-1,4)<br>
if we dont scale - and then calculate - if training points are -<br>
1 - 1200     4 <br>
2 - 1300     4 <br>
3 - 1250     2 <br>

logically 1 and 2 are the nearest (in terms of Euclidean Distance) but if we dont scale we will get 1 and 3 to be nearest as the larger range value overwhelms the noofbedrooms feature

This will be for __min max scaling__ <br>
In this we have for feature __x<sub>i</sub>__  <br>
## x<sub>i</sub><sup>new</sup> as (x<sub>i</sub><sup>old</sup>-x<sub>i</sub><sup>min</sup>)/(x<sub>i</sub><sup>max</sup>-x<sub>i</sub><sup>min</sup>)
The range will be between 0-1

Another way is to subtract is to __subtract ximean from all values to get mean as 0 and rest as +ve or -ve around it__ <br>

To change range from (0-1) to some (min-max) , we do <br>

__val in (0-1) * (max-min) + (min)__

In [5]:
#feature learning in sklearn
import numpy as np
from sklearn import preprocessing

x = np.array([[1,-1,2],[2,0,0],[0,1,-1]], dtype = "float64")

In [7]:
x_scaled = preprocessing.scale(x)

print(x_scaled)
print(x_scaled.mean(axis = 0)) # for row-wise
print(x_scaled.std(axis = 0)) #for row wise

#see how mean has been made 0 for all rows and standard deviation is 1

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]
[0. 0. 0.]
[1. 1. 1.]


The problem with the above scale function is that , usually we have a training data and a testing data ... doing scale on test and train data sperately seems wrong since different operations are happening since the mean etc are different for the training and testing data ... hence we should always scale first and then split <br>
<br>
One case is where the testing data is provided later on , so what we want to do is that scale training data , store the parameters of the training and then use the same parameters on the testing data ... however this is not possible with scale() function , so use StandardScaler

In [8]:
scaler = preprocessing.StandardScaler() #we have a lot of parameters on this , mean , min, max etc
scaler.fit(x) #this will fit the parameters of scaling into scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

In [10]:
#now we can transform various different data based on these parameters using transform function

print(scaler.transform(x)) #gives same value as .scale() function as well

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [14]:
newdata = np.array([[1,1,0]], dtype="float64")
print(scaler.transform(newdata))

[[ 0.          1.22474487 -0.26726124]]
