In [3]:
#datatype is always same in numpy arrays hence less memory is taken also since numpy is itself coded in c , so it is faster
#create numpy arrays
import numpy as np
import math
l = [1,2,3]
print(np.array(l))
l1 = [1,2,"3"]
print(np.array(l1), type(np.array(l1)[0]))

a =  np.zeros(10)
print(a, type(a[0]), a.dtype)
print(a.shape)
b =np.ones(10,int)
print(b, type(b[0]))

#2d arrays , give tuple as argument or soforth for multidimensional arrays

c =  np.zeros((3,4),int)
c[2][2] ="1" #convert string 1 to int 1 
print(c)

#slicing is also allowed 
print(a[2:6])
#slicing in 2d
print(c[:,2]) #gives entire column of index 2

#To know the shape / dimensions 
print(c.shape)

print(np.arange(10))


[1 2 3]
['1' '2' '3'] <class 'numpy.str_'>
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] <class 'numpy.float64'> float64
(10,)
[1 1 1 1 1 1 1 1 1 1] <class 'numpy.int32'>
[[0 0 0 0]
 [0 0 0 0]
 [0 0 1 0]]
[0. 0. 0. 0.]
[0 0 1]
(3, 4)
[0 1 2 3 4 5 6 7 8 9]


In [4]:
#Operations
#in python lists , we cant add integer to list , but in np arrays , we add the scalar(int) to each element of array
m = [1,2,3]
k = [2,3,4]
l = np.array([1,2,3])
n = np.array([2,3,4])
#print(m+1)  gives error for python list
print(l+1)
print(l+n) #gives element wise addition
print(m+k) #gives append wala kaam
print(2*m) #prints lsit twice
print(2*l) #multiplies each element by 2
print(l**2)
print(l**n)
#print(m**2) gives error 

#mean and sum
print(n.mean())
print(n.sum())

#Euclidean distance in a 3d space
a = np.array([4,5,2])
b = np.array([1,2,9])
d = (a-b)**2
print(d)
dist = math.sqrt(d.sum())
print(dist)

#standard deviation
x = np.array([1,2,3,4,5])
x = (x - x.mean())**2
print(x.sum())

#dot product
a1 = np.array([[1,2],[1,2]])
a2 = np.array([[2,1],[2,1]])
print(a1.dot(a2))

a = np.array([0, 1, 2, 3])
b = np.array([2, 3, 4, 5])
print(a.dot(b))

#matrices useful for dieect matrix products extra , given as np.mat()

[2 3 4]
[3 5 7]
[1, 2, 3, 2, 3, 4]
[1, 2, 3, 1, 2, 3]
[2 4 6]
[1 4 9]
[ 1  8 81]
3.0
9
[ 9  9 49]
8.18535277187245
10.0
[[6 3]
 [6 3]]
26


In [5]:
#pandas
import pandas as pd
iris = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data")
print(type(iris))
#first row is taken by pandas as column headers

<class 'pandas.core.frame.DataFrame'>


In [6]:
#make a copy
ds = iris #shallow copy , only gives reference

#gives the deep copy of the dataframe
df = iris.copy()

#to see initial few entries of the data
print(df.head(5)) #argument is optional to get initial number of rows

#similarly we have df.tail() as well


   5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa


In [7]:
#get the current column headers
print(df.columns)

#to correct the column headers
df.columns = ["sl","sw","pl","pw","flower_type"]
print(df.columns)


Index(['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'], dtype='object')
Index(['sl', 'sw', 'pl', 'pw', 'flower_type'], dtype='object')


In [8]:
#to see the shape of the data
print(df.shape)

#to see the datatypes of the data - for each column
print(df.dtypes)

(149, 5)
sl             float64
sw             float64
pl             float64
pw             float64
flower_type     object
dtype: object


In [9]:
#One of the most useful functions to describe the data -  tells us how many nan's are there , mean etc will be found
print(df.describe())
#count tells us how many entries are definite (not nan)
#mean, standard deviation , minimum value , maximum value , spread of value (percentile values - 25 , 50 , 75)

               sl          sw          pl          pw
count  149.000000  149.000000  149.000000  149.000000
mean     5.848322    3.051007    3.774497    1.205369
std      0.828594    0.433499    1.759651    0.761292
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.400000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000


In [10]:
#to access a particular column , we can directly access as - df.columnname or df["columnname"]
print(df.sl)
print(df["sl"])

0      4.9
1      4.7
2      4.6
3      5.0
4      5.4
5      4.6
6      5.0
7      4.4
8      4.9
9      5.4
10     4.8
11     4.8
12     4.3
13     5.8
14     5.7
15     5.4
16     5.1
17     5.7
18     5.1
19     5.4
20     5.1
21     4.6
22     5.1
23     4.8
24     5.0
25     5.0
26     5.2
27     5.2
28     4.7
29     4.8
      ... 
119    6.9
120    5.6
121    7.7
122    6.3
123    6.7
124    7.2
125    6.2
126    6.1
127    6.4
128    7.2
129    7.4
130    7.9
131    6.4
132    6.3
133    6.1
134    7.7
135    6.3
136    6.4
137    6.0
138    6.9
139    6.7
140    6.9
141    5.8
142    6.8
143    6.7
144    6.7
145    6.3
146    6.5
147    6.2
148    5.9
Name: sl, Length: 149, dtype: float64
0      4.9
1      4.7
2      4.6
3      5.0
4      5.4
5      4.6
6      5.0
7      4.4
8      4.9
9      5.4
10     4.8
11     4.8
12     4.3
13     5.8
14     5.7
15     5.4
16     5.1
17     5.7
18     5.1
19     5.4
20     5.1
21     4.6
22     5.1
23     4.8
24     5.0
25     5.0
26   

In [11]:
#is null tells us if an entry is null
print(df.isnull())

        sl     sw     pl     pw  flower_type
0    False  False  False  False        False
1    False  False  False  False        False
2    False  False  False  False        False
3    False  False  False  False        False
4    False  False  False  False        False
5    False  False  False  False        False
6    False  False  False  False        False
7    False  False  False  False        False
8    False  False  False  False        False
9    False  False  False  False        False
10   False  False  False  False        False
11   False  False  False  False        False
12   False  False  False  False        False
13   False  False  False  False        False
14   False  False  False  False        False
15   False  False  False  False        False
16   False  False  False  False        False
17   False  False  False  False        False
18   False  False  False  False        False
19   False  False  False  False        False
20   False  False  False  False        False
21   False

In [12]:
#since checking each entry for null is difficult , do sum that gives for each column number of entries that are null
print(df.isnull().sum())

sl             0
sw             0
pl             0
pw             0
flower_type    0
dtype: int64


In [13]:
#to access data slice (parts of data from the daat frame)
print(df.iloc[1:4 , 2:4]) #works on the basis of position not label
print(df.loc[2]) #wprks pm the basis of label not position
#the above gives rows 1,2,3 [slice is 1:4] and columns 2,3 [slice is 2:4]

    pl   pw
1  1.3  0.2
2  1.5  0.2
3  1.4  0.2
sl                     4.6
sw                     3.1
pl                     1.5
pw                     0.2
flower_type    Iris-setosa
Name: 2, dtype: object


In [14]:
#removing rows from the data we have drop function (only drops row with label as argument)(labels dont get updated once the dataframe has been loaded)
a = df.drop(1)
#this doesnt do in place removal , makes a copy of the data and removes the argument row with label from the copy
print(df.head(2),"\n",a.head(2))

#to make it inplace , we have 2nd argument as well 
df.drop(0,inplace = True)

print(df.head(2))

    sl   sw   pl   pw  flower_type
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa 
     sl   sw   pl   pw  flower_type
0  4.9  3.0  1.4  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
    sl   sw   pl   pw  flower_type
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa


In [15]:
#to find what all labels/indices are present in the dataframe
print(df.index)

Int64Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
            ...
            139, 140, 141, 142, 143, 144, 145, 146, 147, 148],
           dtype='int64', length=148)


In [16]:
print(df.index[0])
#to find the label of first row present in the dataframe
#hence to remove first rows in terms of position
df.drop(df.index[[0,1,2]])

1


sl   sw   pl   pw     flower_type
4    5.4  3.9  1.7  0.4     Iris-setosa
5    4.6  3.4  1.4  0.3     Iris-setosa
6    5.0  3.4  1.5  0.2     Iris-setosa
7    4.4  2.9  1.4  0.2     Iris-setosa
8    4.9  3.1  1.5  0.1     Iris-setosa
9    5.4  3.7  1.5  0.2     Iris-setosa
10   4.8  3.4  1.6  0.2     Iris-setosa
11   4.8  3.0  1.4  0.1     Iris-setosa
12   4.3  3.0  1.1  0.1     Iris-setosa
13   5.8  4.0  1.2  0.2     Iris-setosa
14   5.7  4.4  1.5  0.4     Iris-setosa
15   5.4  3.9  1.3  0.4     Iris-setosa
16   5.1  3.5  1.4  0.3     Iris-setosa
17   5.7  3.8  1.7  0.3     Iris-setosa
18   5.1  3.8  1.5  0.3     Iris-setosa
19   5.4  3.4  1.7  0.2     Iris-setosa
20   5.1  3.7  1.5  0.4     Iris-setosa
21   4.6  3.6  1.0  0.2     Iris-setosa
22   5.1  3.3  1.7  0.5     Iris-setosa
23   4.8  3.4  1.9  0.2     Iris-setosa
24   5.0  3.0  1.6  0.2     Iris-setosa
25   5.0  3.4  1.6  0.4     Iris-setosa
26   5.2  3.5  1.5  0.2     Iris-setosa
27   5.2  3.4  1.4  0.2     Iris-setosa
28   4.7  3.2  1.6  0.2     Iris-setosa
29   4.8  3.1  1.6  0.2     Iris-setosa
30   5.4  3.4  1.5  0.4     Iris-setosa
31   5.2  4.1  1.5  0.1     Iris-setosa
32   5.5  4.2  1.4  0.2     Iris-setosa
33   4.9  3.1  1.5  0.1     Iris-setosa
..   ...  ...  ...  ...             ...
119  6.9  3.2  5.7  2.3  Iris-virginica
120  5.6  2.8  4.9  2.0  Iris-virginica
121  7.7  2.8  6.7  2.0  Iris-virginica
122  6.3  2.7  4.9  1.8  Iris-virginica
123  6.7  3.3  5.7  2.1  Iris-virginica
124  7.2  3.2  6.0  1.8  Iris-virginica
125  6.2  2.8  4.8  1.8  Iris-virginica
126  6.1  3.0  4.9  1.8  Iris-virginica
127  6.4  2.8  5.6  2.1  Iris-virginica
128  7.2  3.0  5.8  1.6  Iris-virginica
129  7.4  2.8  6.1  1.9  Iris-virginica
130  7.9  3.8  6.4  2.0  Iris-virginica
131  6.4  2.8  5.6  2.2  Iris-virginica
132  6.3  2.8  5.1  1.5  Iris-virginica
133  6.1  2.6  5.6  1.4  Iris-virginica
134  7.7  3.0  6.1  2.3  Iris-virginica
135  6.3  3.4  5.6  2.4  Iris-virginica
136  6.4  3.1  5.5  1.8  Iris-virginica
137  6.0  3.0  4.8  1.8  Iris-virginica
138  6.9  3.1  5.4  2.1  Iris-virginica
139  6.7  3.1  5.6  2.4  Iris-virginica
140  6.9  3.1  5.1  2.3  Iris-virginica
141  5.8  2.7  5.1  1.9  Iris-virginica
142  6.8  3.2  5.9  2.3  Iris-virginica
143  6.7  3.3  5.7  2.5  Iris-virginica
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[145 rows x 5 columns]

In [17]:
#relational operators
print(df.sl > 5) # based on values gives row labels and true or false



1      False
2      False
3      False
4       True
5      False
6      False
7      False
8      False
9       True
10     False
11     False
12     False
13      True
14      True
15      True
16      True
17      True
18      True
19      True
20      True
21     False
22      True
23     False
24     False
25     False
26      True
27      True
28     False
29     False
30      True
       ...  
119     True
120     True
121     True
122     True
123     True
124     True
125     True
126     True
127     True
128     True
129     True
130     True
131     True
132     True
133     True
134     True
135     True
136     True
137     True
138     True
139     True
140     True
141     True
142     True
143     True
144     True
145     True
146     True
147     True
148     True
Name: sl, Length: 148, dtype: bool


In [18]:
#also to only get rows which satisfy a particular condition , we can use 
print(df[df.sl>6])

      sl   sw   pl   pw      flower_type
49   7.0  3.2  4.7  1.4  Iris-versicolor
50   6.4  3.2  4.5  1.5  Iris-versicolor
51   6.9  3.1  4.9  1.5  Iris-versicolor
53   6.5  2.8  4.6  1.5  Iris-versicolor
55   6.3  3.3  4.7  1.6  Iris-versicolor
57   6.6  2.9  4.6  1.3  Iris-versicolor
62   6.1  2.9  4.7  1.4  Iris-versicolor
64   6.7  3.1  4.4  1.4  Iris-versicolor
67   6.2  2.2  4.5  1.5  Iris-versicolor
70   6.1  2.8  4.0  1.3  Iris-versicolor
71   6.3  2.5  4.9  1.5  Iris-versicolor
72   6.1  2.8  4.7  1.2  Iris-versicolor
73   6.4  2.9  4.3  1.3  Iris-versicolor
74   6.6  3.0  4.4  1.4  Iris-versicolor
75   6.8  2.8  4.8  1.4  Iris-versicolor
76   6.7  3.0  5.0  1.7  Iris-versicolor
85   6.7  3.1  4.7  1.5  Iris-versicolor
86   6.3  2.3  4.4  1.3  Iris-versicolor
90   6.1  3.0  4.6  1.4  Iris-versicolor
96   6.2  2.9  4.3  1.3  Iris-versicolor
99   6.3  3.3  6.0  2.5   Iris-virginica
101  7.1  3.0  5.9  2.1   Iris-virginica
102  6.3  2.9  5.6  1.8   Iris-virginica
103  6.5  3.0  5

In [19]:
#to add a row
df.loc[0] = [1,2,3,4,"Iris-setosa"]
print(df.tail(2))

      sl   sw   pl   pw     flower_type
148  5.9  3.0  5.1  1.8  Iris-virginica
0    1.0  2.0  3.0  4.0     Iris-setosa


In [20]:
#since our indexes/labels are very weird because of deletion etc, we can reset them
print(df.index)
ab = df.copy()
ab.reset_index()
#the reset_index goves us the indices reset(labels) but adds the old indices into a new column
#also this is not inplace , we have to do (inplace = True)
#if we dont want that to happen , add argument(drop = True)

Int64Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
            ...
            140, 141, 142, 143, 144, 145, 146, 147, 148,   0],
           dtype='int64', length=149)


index   sl   sw   pl   pw     flower_type
0        1  4.7  3.2  1.3  0.2     Iris-setosa
1        2  4.6  3.1  1.5  0.2     Iris-setosa
2        3  5.0  3.6  1.4  0.2     Iris-setosa
3        4  5.4  3.9  1.7  0.4     Iris-setosa
4        5  4.6  3.4  1.4  0.3     Iris-setosa
5        6  5.0  3.4  1.5  0.2     Iris-setosa
6        7  4.4  2.9  1.4  0.2     Iris-setosa
7        8  4.9  3.1  1.5  0.1     Iris-setosa
8        9  5.4  3.7  1.5  0.2     Iris-setosa
9       10  4.8  3.4  1.6  0.2     Iris-setosa
10      11  4.8  3.0  1.4  0.1     Iris-setosa
11      12  4.3  3.0  1.1  0.1     Iris-setosa
12      13  5.8  4.0  1.2  0.2     Iris-setosa
13      14  5.7  4.4  1.5  0.4     Iris-setosa
14      15  5.4  3.9  1.3  0.4     Iris-setosa
15      16  5.1  3.5  1.4  0.3     Iris-setosa
16      17  5.7  3.8  1.7  0.3     Iris-setosa
17      18  5.1  3.8  1.5  0.3     Iris-setosa
18      19  5.4  3.4  1.7  0.2     Iris-setosa
19      20  5.1  3.7  1.5  0.4     Iris-setosa
20      21  4.6  3.6  1.0  0.2     Iris-setosa
21      22  5.1  3.3  1.7  0.5     Iris-setosa
22      23  4.8  3.4  1.9  0.2     Iris-setosa
23      24  5.0  3.0  1.6  0.2     Iris-setosa
24      25  5.0  3.4  1.6  0.4     Iris-setosa
25      26  5.2  3.5  1.5  0.2     Iris-setosa
26      27  5.2  3.4  1.4  0.2     Iris-setosa
27      28  4.7  3.2  1.6  0.2     Iris-setosa
28      29  4.8  3.1  1.6  0.2     Iris-setosa
29      30  5.4  3.4  1.5  0.4     Iris-setosa
..     ...  ...  ...  ...  ...             ...
119    120  5.6  2.8  4.9  2.0  Iris-virginica
120    121  7.7  2.8  6.7  2.0  Iris-virginica
121    122  6.3  2.7  4.9  1.8  Iris-virginica
122    123  6.7  3.3  5.7  2.1  Iris-virginica
123    124  7.2  3.2  6.0  1.8  Iris-virginica
124    125  6.2  2.8  4.8  1.8  Iris-virginica
125    126  6.1  3.0  4.9  1.8  Iris-virginica
126    127  6.4  2.8  5.6  2.1  Iris-virginica
127    128  7.2  3.0  5.8  1.6  Iris-virginica
128    129  7.4  2.8  6.1  1.9  Iris-virginica
129    130  7.9  3.8  6.4  2.0  Iris-virginica
130    131  6.4  2.8  5.6  2.2  Iris-virginica
131    132  6.3  2.8  5.1  1.5  Iris-virginica
132    133  6.1  2.6  5.6  1.4  Iris-virginica
133    134  7.7  3.0  6.1  2.3  Iris-virginica
134    135  6.3  3.4  5.6  2.4  Iris-virginica
135    136  6.4  3.1  5.5  1.8  Iris-virginica
136    137  6.0  3.0  4.8  1.8  Iris-virginica
137    138  6.9  3.1  5.4  2.1  Iris-virginica
138    139  6.7  3.1  5.6  2.4  Iris-virginica
139    140  6.9  3.1  5.1  2.3  Iris-virginica
140    141  5.8  2.7  5.1  1.9  Iris-virginica
141    142  6.8  3.2  5.9  2.3  Iris-virginica
142    143  6.7  3.3  5.7  2.5  Iris-virginica
143    144  6.7  3.0  5.2  2.3  Iris-virginica
144    145  6.3  2.5  5.0  1.9  Iris-virginica
145    146  6.5  3.0  5.2  2.0  Iris-virginica
146    147  6.2  3.4  5.4  2.3  Iris-virginica
147    148  5.9  3.0  5.1  1.8  Iris-virginica
148      0  1.0  2.0  3.0  4.0     Iris-setosa

[149 rows x 6 columns]

In [21]:
#to delete columns 
ab.drop("sl", axis = 1 , inplace = True)
#axis = 1 makes it a column deletion , inplace for inplace deletion , and column name is needed for deletion
print(ab.head())

#2nd way of deletion is 
del ab["sw"]
print(ab.head())

    sw   pl   pw  flower_type
1  3.2  1.3  0.2  Iris-setosa
2  3.1  1.5  0.2  Iris-setosa
3  3.6  1.4  0.2  Iris-setosa
4  3.9  1.7  0.4  Iris-setosa
5  3.4  1.4  0.3  Iris-setosa
    pl   pw  flower_type
1  1.3  0.2  Iris-setosa
2  1.5  0.2  Iris-setosa
3  1.4  0.2  Iris-setosa
4  1.7  0.4  Iris-setosa
5  1.4  0.3  Iris-setosa


In [22]:
#to add a column that is like difference of two rows ,sum , multiply etc or a constant df["col"] = 1
ab = df.copy()
ab["diff"] = ab["sl"] - ab["pw"]
print(ab.head())

    sl   sw   pl   pw  flower_type  diff
1  4.7  3.2  1.3  0.2  Iris-setosa   4.5
2  4.6  3.1  1.5  0.2  Iris-setosa   4.4
3  5.0  3.6  1.4  0.2  Iris-setosa   4.8
4  5.4  3.9  1.7  0.4  Iris-setosa   5.0
5  4.6  3.4  1.4  0.3  Iris-setosa   4.3


In [23]:
#handling NAN
import numpy as np
df.iloc[2:4,1:3] = np.nan   #first make it nan since no entry in the given dataset is nan

In [24]:
print(df.describe())
#the count of columns 1 and 2 have gone down since we inserted NAN in there



               sl          sw          pl          pw
count  149.000000  147.000000  147.000000  149.000000
mean     5.822148    3.034694    3.815646    1.230872
std      0.915766    0.436777    1.741976    0.790475
min      1.000000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.400000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    4.000000


In [25]:
#one way to handle is to remove the rows that have nan values
df.dropna()
#this has removed the rows 2,3 (labels 3,4) which had nan values (again inplace = True is needed for change to be made in df)

sl   sw   pl   pw     flower_type
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
5    4.6  3.4  1.4  0.3     Iris-setosa
6    5.0  3.4  1.5  0.2     Iris-setosa
7    4.4  2.9  1.4  0.2     Iris-setosa
8    4.9  3.1  1.5  0.1     Iris-setosa
9    5.4  3.7  1.5  0.2     Iris-setosa
10   4.8  3.4  1.6  0.2     Iris-setosa
11   4.8  3.0  1.4  0.1     Iris-setosa
12   4.3  3.0  1.1  0.1     Iris-setosa
13   5.8  4.0  1.2  0.2     Iris-setosa
14   5.7  4.4  1.5  0.4     Iris-setosa
15   5.4  3.9  1.3  0.4     Iris-setosa
16   5.1  3.5  1.4  0.3     Iris-setosa
17   5.7  3.8  1.7  0.3     Iris-setosa
18   5.1  3.8  1.5  0.3     Iris-setosa
19   5.4  3.4  1.7  0.2     Iris-setosa
20   5.1  3.7  1.5  0.4     Iris-setosa
21   4.6  3.6  1.0  0.2     Iris-setosa
22   5.1  3.3  1.7  0.5     Iris-setosa
23   4.8  3.4  1.9  0.2     Iris-setosa
24   5.0  3.0  1.6  0.2     Iris-setosa
25   5.0  3.4  1.6  0.4     Iris-setosa
26   5.2  3.5  1.5  0.2     Iris-setosa
27   5.2  3.4  1.4  0.2     Iris-setosa
28   4.7  3.2  1.6  0.2     Iris-setosa
29   4.8  3.1  1.6  0.2     Iris-setosa
30   5.4  3.4  1.5  0.4     Iris-setosa
31   5.2  4.1  1.5  0.1     Iris-setosa
32   5.5  4.2  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
120  5.6  2.8  4.9  2.0  Iris-virginica
121  7.7  2.8  6.7  2.0  Iris-virginica
122  6.3  2.7  4.9  1.8  Iris-virginica
123  6.7  3.3  5.7  2.1  Iris-virginica
124  7.2  3.2  6.0  1.8  Iris-virginica
125  6.2  2.8  4.8  1.8  Iris-virginica
126  6.1  3.0  4.9  1.8  Iris-virginica
127  6.4  2.8  5.6  2.1  Iris-virginica
128  7.2  3.0  5.8  1.6  Iris-virginica
129  7.4  2.8  6.1  1.9  Iris-virginica
130  7.9  3.8  6.4  2.0  Iris-virginica
131  6.4  2.8  5.6  2.2  Iris-virginica
132  6.3  2.8  5.1  1.5  Iris-virginica
133  6.1  2.6  5.6  1.4  Iris-virginica
134  7.7  3.0  6.1  2.3  Iris-virginica
135  6.3  3.4  5.6  2.4  Iris-virginica
136  6.4  3.1  5.5  1.8  Iris-virginica
137  6.0  3.0  4.8  1.8  Iris-virginica
138  6.9  3.1  5.4  2.1  Iris-virginica
139  6.7  3.1  5.6  2.4  Iris-virginica
140  6.9  3.1  5.1  2.3  Iris-virginica
141  5.8  2.7  5.1  1.9  Iris-virginica
142  6.8  3.2  5.9  2.3  Iris-virginica
143  6.7  3.3  5.7  2.5  Iris-virginica
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica
0    1.0  2.0  3.0  4.0     Iris-setosa

[147 rows x 5 columns]

In [26]:
#other option is to fill with mean , mode etc
df.sw.fillna(df.sw.mean())
#rows with label 3,4 have been filled with mean (inplace = True is needed for the inplace change)

1      3.200000
2      3.100000
3      3.034694
4      3.034694
5      3.400000
6      3.400000
7      2.900000
8      3.100000
9      3.700000
10     3.400000
11     3.000000
12     3.000000
13     4.000000
14     4.400000
15     3.900000
16     3.500000
17     3.800000
18     3.800000
19     3.400000
20     3.700000
21     3.600000
22     3.300000
23     3.400000
24     3.000000
25     3.400000
26     3.500000
27     3.400000
28     3.200000
29     3.100000
30     3.400000
         ...   
120    2.800000
121    2.800000
122    2.700000
123    3.300000
124    3.200000
125    2.800000
126    3.000000
127    2.800000
128    3.000000
129    2.800000
130    3.800000
131    2.800000
132    2.800000
133    2.600000
134    3.000000
135    3.400000
136    3.100000
137    3.000000
138    3.100000
139    3.100000
140    3.100000
141    2.700000
142    3.200000
143    3.300000
144    3.000000
145    2.500000
146    3.000000
147    3.400000
148    3.000000
0      2.000000
Name: sw, Length: 149, d

In [28]:
#handling strings in data
df["Gender"] = "Female"
print(df.head())
df.iloc[1:3,5] = "Male"
print(df.head())

    sl   sw   pl   pw  flower_type  Gender
1  4.7  3.2  1.3  0.2  Iris-setosa  Female
2  4.6  3.1  1.5  0.2  Iris-setosa  Female
3  5.0  NaN  NaN  0.2  Iris-setosa  Female
4  5.4  NaN  NaN  0.4  Iris-setosa  Female
5  4.6  3.4  1.4  0.3  Iris-setosa  Female
    sl   sw   pl   pw  flower_type  Gender
1  4.7  3.2  1.3  0.2  Iris-setosa  Female
2  4.6  3.1  1.5  0.2  Iris-setosa    Male
3  5.0  NaN  NaN  0.2  Iris-setosa    Male
4  5.4  NaN  NaN  0.4  Iris-setosa  Female
5  4.6  3.4  1.4  0.3  Iris-setosa  Female


In [29]:
def fun(x):
    if(x=="Male"):
        return 1
    else:
        return 0
df["integer_gender"] = df.Gender.apply(fun)
print(df.head())

    sl   sw   pl   pw  flower_type  Gender  integer_gender
1  4.7  3.2  1.3  0.2  Iris-setosa  Female               0
2  4.6  3.1  1.5  0.2  Iris-setosa    Male               1
3  5.0  NaN  NaN  0.2  Iris-setosa    Male               1
4  5.4  NaN  NaN  0.4  Iris-setosa  Female               0
5  4.6  3.4  1.4  0.3  Iris-setosa  Female               0


In [ ]:
""" aim for the preprocessor -
1 find useful columns
2 if they need data preprocess (nan , avgs etc)
3 drop useless ones / add new ones
4 string to integers etc """